version: 2.1
orbs:
  node: circleci/node@3.0.1
  docker: circleci/docker@0.5.19
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: '16.13.1'
      - docker/install-docker
      - run: node --version
      - run: python --version
      - run: npm --version
      - run: docker --version
      - run: env
      - node/install-packages
      - run: npm install --no-save tap-xunit
      - run: mkdir -p _out/unit _out/e2e
      - run: npm test --  --timeout=1m --tap| npx tap-xunit > _out/unit/test.xml
      - run: npm run build
      - run: npm run test:e2e --  --timeout=1m --tap| npx tap-xunit > _out/e2e/test.xml
      - store_test_results:
          path: _out
      - store_artifacts:
          path: _out

  build-and-release:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: '12.18.0'
      - docker/install-docker
      - run: ./boyar/create-version-file.sh
      - node/install-packages
      - run: ./boyar/docker-build.sh
      - run: ./.circleci/release.sh

  build-and-release-to-staging:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: '12.18.0'
      - docker/install-docker
      - run: ./boyar/create-version-file.sh
      - node/install-packages
      - run: ./boyar/docker-build.sh
      - run: ./.circleci/release-to-staging.sh

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - build-and-release-to-staging:
            filters:
              branches:
                only: /.*/
              tags:
                only: /v.*/
